# Generated by Django 5.2.4 on 2026-03-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_cardprogress_reviewhistory_delete_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['-created_at']},
        ),
    ]
