# Generated by Django 5.2.4 on 2026-05-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_deck_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('question', ''), _negated=True), name='question_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('answer', ''), _negated=True), name='answer_not_empty'),
        ),
    ]
