# Generated by Django 5.2.4 on 2026-03-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cards_reviwed',
            new_name='cards_reviewed',
        ),
    ]
